---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(rvest)
source("functions/get_file_list.R")
source("functions/safe_download_file.R")
```

```{r}
url<-"http://archive.luftdaten.info/parquet/"

list_of_parquet_files<-get_file_list(url) %>%
  mutate(url=paste0(url,name)) %>%
  group_by(url) %>%
  do(get_file_list(.$url)) %>%
  ungroup() %>%
  mutate(url=paste0(url,name)) %>%
  group_by(url) %>%
  do(get_file_list(.$url)) %>%
  ungroup() %>%
  mutate(url=paste0(url,name)) %>%
  filter(name!="_SUCCESS")
```



```{r}
local_folder_path<-"J:/luftdaten_parquet/"

local_files<-tibble(name=list.files(local_folder_path))
```


```{r}
download_report<-list_of_parquet_files %>%
  anti_join(local_files) %>%
  #filter(name=="part-00000-54e040bf-d929-489f-aa97-128e727c5aa0-c000.snappy.parquet") %>%
  group_by(name,url) %>%
  do(safe_download_file(.$url,.$name,local_folder_path))
```

```{r}
library(sparklyr)
#spark_uninstall(version="2.1.0",hadoop_version="2.7")
spark_install(version="2.4.3")
sc <- spark_connect(master = "local")
```

```{r}
luftdaten_df<-spark_read_parquet(sc,"luftdaten","C:/luftdaten_parquet_subset",memory=FALSE)

```

```{r}
# Set the system environment variables
Sys.setenv(SPARK_HOME = "C:/Users/Bob/AppData/Local/spark")
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()))

#load the Sparkr library
library(SparkR)

sparkR.session(master = "local[*]", sparkConfig = list(spark.driver.memory = "2g"))
```


