---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(rvest)
library(tidyverse)
```



```{r}
make_sensor_list<-function(day){
  folder_url<-paste0("http://archive.luftdaten.info/",day,"/")
  tibble(sensor_file=read_html(folder_url) %>%
    html_nodes("a") %>%
    html_attr("href")) %>%
    filter(sensor_file %>% str_detect(".csv")) %>%
    mutate(file_url=paste0(folder_url,sensor_file)) %>%
    separate(sensor_file,into=c("date","sensor_type",NA,"sensor_id","indoor"),sep="_",remove=FALSE) %>%
    mutate(sensor_id=str_remove_all(sensor_id,".csv"),
           indoor=str_replace_all(indoor,"indoor.csv","TRUE"),
           indoor=replace_na(indoor,"FALSE")) %>%
  return()
}


```

```{r}
start_day=ymd("2015-10-01") #first ever day
#start_day=ymd("2019-01-01")
#stop_day=ymd("2019-06-30")
stop_day=ymd(today())

sensor_list<-tibble(day=seq(start_day,stop_day,by='month')) %>%
  group_by(day) %>%
  do(make_sensor_list(.$day))

```

```{r}
first_day_list<-sensor_list %>%
  group_by(sensor_id) %>%
  summarise(first_day=min(day)) %>%
  left_join(sensor_list,by=c("sensor_id"="sensor_id","first_day"="day")) %>%
  mutate(sensor_id=as.numeric(sensor_id))
```


```{r message=FALSE}
if(!exists("sensor_details")){
  sensor_details=data.frame(first_day=as_date(character()),sensor_id=as.numeric(character()))
}

missing_sensors<-first_day_list %>%
  anti_join(sensor_details,by=c("first_day","sensor_id"))

sensor_details %<>%  bind_rows(missing_sensors[1:5000,] %>%
                      group_by(first_day,sensor_file) %>%
                      do(read_delim(.$file_url,";",n_max=1)))

write_csv(sensor_details,"sensor_details.csv")

```


```{r}
sensor_list_details<-sensor_list %>%
  mutate(sensor_id=as.numeric(sensor_id)) %>%
  inner_join(sensor_details %>% select(sensor_id,location,lat,lon)
             ,by="sensor_id")
  
write_csv(sensor_list_details,"sensor_list_details.csv")
```

```{r}
library(ggmap)
library(maps)
library(mapdata)
library(gganimate)
```


```{r}
europe <- c(
  "Portugal", "Spain", "France", "Switzerland", "Germany",
  "Austria", "Belgium", "UK", "Netherlands",
  "Denmark", "Poland", "Italy", 
  "Croatia", "Slovenia", "Hungary", "Slovakia",
  "Czech republic","Norway","Sweden","Finland","Greece"
)
my_map<-map_data("world")
```

```{r, fig.width=12}
ggplot() +
  geom_polygon(data = my_map, aes(x=long, y = lat, group = group), fill="white")+
  geom_bin2d(data=sensor_list_details,aes(x = lon, y = lat),bins=c(200,100),alpha=.5)+
  #coord_map(xlim=c(-25,25),ylim=c(30,70))
  scale_size_area(max_size = 5)+
  scale_fill_viridis_c()+
  coord_quickmap()+
  transition_states(day,transition_length = 2,state_length = 1)
```



